### ISSUE TITLE
Unable to decrypt old data after on-demand key rotation

### ISSUE THREAD

**Issue by motica1** [aws/aws-database-encryption-sdk-dynamodb#1395]
Ran on-demand key rotation for KMS customer key that we use and are no longer able to decrypt the old data.

The error observed is: 

```
{
            "detail": "Unable to unmarshall response (No Configured Keyring was able to decrypt the Data Key. The list of encountered Exceptions is available via `list`.). Response Code: 200, Response Text: OK"
        }
```

 Can you clarify if that is expected behaviour?

**Comment by josecorella** [comment]
Hi @motica1!

Could you share more details on your setup and maybe a code example that shows which keyring you are using.
Thanks!

**Comment by motica1** [comment]
Hey @josecorella I found the issue was with the alias being used.
