### ISSUE TITLE
"allowedUnsigned*" name inconsistency

### ISSUE THREAD

**Issue by lavaleri** [aws/aws-database-encryption-sdk-dynamodb#528]
The API and docs use the following two params names:
- allowedUnsignedAttributes
- allowedUnsignedAttributePrefix

However these same params are referred to as the following in the specification, and in error messaging:
- allowedUnauthenticatedAttributes
- allowedUnauthenticatedAttributePrefix.

This repo should be updated to use the API/docs naming.

**Comment by ajewellamz** [comment]
I guess we fixed this a whole ago, because allowedUnauthenticatedAttributes appears nowhere in the specification, or error messaging
