### ISSUE TITLE
Transactional write calls on encrypted + unencrypted table

### ISSUE THREAD

**Issue by motica1** [aws/aws-database-encryption-sdk-dynamodb#722]
Hi Team, 

I have a use case where I need to make transactional put calls for an encrypted table and in an unencrypted table. Looking at the following [reference](https://stackoverflow.com/questions/75813542/insert-multiple-records-into-multiple-tables-using-dynamo-db-transactions-api), I believe i can only use one `AmazonDynamoDB` or `DynamoDbEnhancedClient`. Wondering if i should be using the `DynamoDbEnhancedClient` i have created with an encryption interceptor or not? Would the SDK / transactional call be able to figure out that one table needs an encrypted write and other one does not? 

Thanks in advance!

**Comment by ajewellamz** [comment]
The client you have created with an encryption interceptor should be just fine.

The interceptor configuration configures each table separately. Any unconfigured tables are assumed to be unencrypted, and the interceptor will pass the requests and responses through unchanged
